# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1109k_SFHrzeiR4CVEjfPJGdpk7dx1n4r
"""

import numpy as np
import matplotlib.pyplot as plt
 
 
#Triangle sides
a = 5.5
b = 5.5
c = 5.5
p=(a**2+c**2-b**2)/(2*a)
 
 
#Triangle vertices
A = np.array([p,c]) 
B = np.array([0,0]) 
C = np.array([a,0]) 
 
 
#Generating all lines
x_AB = line_gen(A,B)
x_BC = line_gen(B,C)
x_CA = line_gen(C,A)
 
#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CA[0,:],x_CA[1,:],label='$CA$')
 
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 - 0.01), A[1] * (1 + 0.01) , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1 - 0.02), B[1] * (1) , 'B')
plt.plot(C[0], C[1], 'o')
plt.text(C[0] * (1 + 0.03), C[1] * (1 - 0.1) , 'C')
 
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend(loc='best')
plt.grid() # minor
#else
#plt.show()